version: '3'
services:
  backend:
    build: ./backend
    container_name: magical-wardrobe-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    restart: always

  frontend:
    build: ./frontend
    container_name: magical-wardrobe-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    restart: always
